image: "rust:latest"

stages:
    - lint
    - test

fmt:
    stage: lint
    before_script:
        - rustup component add rustfmt
    script:
        - cargo fmt -- --check

.common: &common
    before_script:
        - VERSION=$(echo "$CI_JOB_NAME" | cut -d ':' -f 2)
        - apt update
        - apt install lxc-dev clang -y

        - git clone https://github.com/lxc/lxc.git
        - cd lxc
        - git checkout "lxc-$VERSION.0"
        - ./autogen.sh
        - ./configure
        - cp src/lxc/attach_options.h src/lxc/lxccontainer.h src/lxc/version.h /usr/include/lxc

.clippy: &clippy
    <<: *common
    stage: lint
    script:
        - rustup component add clippy
        - cargo clippy --features="v${VERSION/./_}"

clippy:1.0:
    <<: *clippy

clippy:1.1:
    <<: *clippy

clippy:2.0:
    <<: *clippy

clippy:2.1:
    <<: *clippy

clippy:3.0:
    <<: *clippy

clippy:3.1:
    <<: *clippy

clippy:3.2:
    <<: *clippy

clippy:4.0:
    <<: *clippy

.test: &test
    <<: *common
    stage: test
    script:
        - FEATURE="v${VERSION/./_}"
        - cargo test --features=$FEATURE --release
        - cargo test --features=$FEATURE

test:1.0:
    <<: *test

test:1.1:
    <<: *test

test:2.0:
    <<: *test

test:2.1:
    <<: *test

test:3.0:
    <<: *test

test:3.1:
    <<: *test

test:3.2:
    <<: *test

test:4.0:
    <<: *test
